export const Product = [
  {
    id: 1,
    title: 'Essence Mascara Lash Princess',
    description:
      'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
    summary: 'The Essence Mascara Lash Princess is ',
    category: 'beauty',
    price: 9.99,
    discountPercentage: 10.48,
    rating: 2.56,
    stock: 99,
    brand: 'Essence',
    weight: 4,
    dimensions: { width: 15.14, height: 13.08, depth: 22.99 },
  },
  {
    id: 2,
    title: 'Eyeshadow Palette with Mirror',
    description:
      "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
    summary: 'The Eyeshadow Palette with Mirror offers ',
    category: 'beauty',
    price: 19.99,
    discountPercentage: 18.19,
    rating: 2.86,
    stock: 34,
    brand: 'Glamour Beauty',
    weight: 9,
    dimensions: { width: 9.26, height: 22.47, depth: 27.67 },
  },
  {
    id: 3,
    title: 'Powder Canister',
    description:
      'The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.',
    summary: 'The Powder Canister is a finely ',
    category: 'beauty',
    price: 14.99,
    discountPercentage: 9.84,
    rating: 4.64,
    stock: 89,
    brand: 'Velvet Touch',
    weight: 8,
    dimensions: { width: 29.27, height: 27.93, depth: 20.59 },
  },
  {
    id: 4,
    title: 'Red Lipstick',
    description:
      'The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.',
    summary: 'The Red Lipstick is a classic ',
    category: 'beauty',
    price: 12.99,
    discountPercentage: 12.16,
    rating: 4.36,
    stock: 91,
    brand: 'Chic Cosmetics',
    weight: 1,
    dimensions: { width: 18.11, height: 28.38, depth: 22.17 },
  },
  {
    id: 5,
    title: 'Red Nail Polish',
    description:
      'The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.',
    summary: 'The Red Nail Polish offers a ',
    category: 'beauty',
    price: 8.99,
    discountPercentage: 11.44,
    rating: 4.32,
    stock: 79,
    brand: 'Nail Couture',
    weight: 8,
    dimensions: { width: 21.63, height: 16.48, depth: 29.84 },
  },
  {
    id: 6,
    title: 'Calvin Klein CK One',
    description:
      "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.",
    summary: 'CK One by Calvin Klein is ',
    category: 'fragrances',
    price: 49.99,
    discountPercentage: 1.89,
    rating: 4.37,
    stock: 29,
    brand: 'Calvin Klein',
    weight: 7,
    dimensions: { width: 29.36, height: 27.76, depth: 20.72 },
  },
  {
    id: 7,
    title: 'Chanel Coco Noir Eau De',
    description:
      'Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.',
    summary: 'Coco Noir by Chanel is an ',
    category: 'fragrances',
    price: 129.99,
    discountPercentage: 16.51,
    rating: 4.26,
    stock: 58,
    brand: 'Chanel',
    weight: 7,
    dimensions: { width: 24.5, height: 25.7, depth: 25.98 },
  },
  {
    id: 8,
    title: "Dior J'adore",
    description:
      "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.",
    summary: "J'adore by Dior is a ",
    category: 'fragrances',
    price: 89.99,
    discountPercentage: 14.72,
    rating: 3.8,
    stock: 98,
    brand: 'Dior',
    weight: 4,
    dimensions: { width: 27.67, height: 28.28, depth: 11.83 },
  },
  {
    id: 9,
    title: 'Dolce Shine Eau de',
    description:
      "Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent.",
    summary: 'Dolce Shine by Dolce & Gabbana ',
    category: 'fragrances',
    price: 69.99,
    discountPercentage: 0.62,
    rating: 3.96,
    stock: 4,
    brand: 'Dolce & Gabbana',
    weight: 6,
    dimensions: { width: 27.28, height: 29.88, depth: 18.3 },
  },
  {
    id: 10,
    title: 'Gucci Bloom Eau de',
    description:
      "Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It's a modern and romantic scent.",
    summary: 'Gucci Bloom by Gucci is a ',
    category: 'fragrances',
    price: 79.99,
    discountPercentage: 14.39,
    rating: 2.74,
    stock: 91,
    brand: 'Gucci',
    weight: 7,
    dimensions: { width: 20.92, height: 21.68, depth: 11.2 },
  },
  {
    id: 11,
    title: 'Annibale Colombo Bed',
    description:
      'The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.',
    summary: 'The Annibale Colombo Bed is a ',
    category: 'furniture',
    price: 1899.99,
    discountPercentage: 8.57,
    rating: 4.77,
    stock: 88,
    brand: 'Annibale Colombo',
    weight: 10,
    dimensions: { width: 28.16, height: 25.36, depth: 17.28 },
  },
  {
    id: 12,
    title: 'Annibale Colombo Sofa',
    description:
      'The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.',
    summary: 'The Annibale Colombo Sofa is a ',
    category: 'furniture',
    price: 2499.99,
    discountPercentage: 14.4,
    rating: 3.92,
    stock: 60,
    brand: 'Annibale Colombo',
    weight: 6,
    dimensions: { width: 12.75, height: 20.55, depth: 19.06 },
  },
  {
    id: 13,
    title: 'Bedside Table African Cherry',
    description:
      'The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.',
    summary: 'The Bedside Table in African Cherry ',
    category: 'furniture',
    price: 299.99,
    discountPercentage: 19.09,
    rating: 2.87,
    stock: 64,
    brand: 'Furniture Co.',
    weight: 2,
    dimensions: { width: 13.47, height: 24.99, depth: 27.35 },
  },
  {
    id: 14,
    title: 'Knoll Saarinen Executive Conference Chair',
    description:
      'The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.',
    summary: 'The Knoll Saarinen Executive Conference Chair ',
    category: 'furniture',
    price: 499.99,
    discountPercentage: 2.01,
    rating: 4.88,
    stock: 26,
    brand: 'Knoll',
    weight: 10,
    dimensions: { width: 13.81, height: 7.5, depth: 5.62 },
  },
  {
    id: 15,
    title: 'Wooden Bathroom Sink With Mirror',
    description:
      'The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.',
    summary: 'The Wooden Bathroom Sink with Mirror ',
    category: 'furniture',
    price: 799.99,
    discountPercentage: 8.8,
    rating: 3.59,
    stock: 7,
    brand: 'Bath Trends',
    weight: 10,
    dimensions: { width: 7.98, height: 8.88, depth: 28.46 },
  },
];
